// <auto-generated />
using System;
using LightStudio.MediaLibraryCore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightStudio.MediaLibraryCore.Migrations
{
    [DbContext(typeof(MediaLibraryDbContext))]
    partial class MediaLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("LightStudio.MediaLibraryCore.Database.Entities.DbMediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Composer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DatabaseItemAddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscNumber")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FileLastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grouping")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Performer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalDiscs")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalTracks")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("LightStudio.MediaLibraryCore.Database.Entities.DbPlaybackHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedMediaFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMediaFileId");

                    b.ToTable("PlaybackHistory");
                });

            modelBuilder.Entity("LightStudio.MediaLibraryCore.Database.Entities.DbPlaybackHistory", b =>
                {
                    b.HasOne("LightStudio.MediaLibraryCore.Database.Entities.DbMediaFile", "RelatedMediaFile")
                        .WithMany()
                        .HasForeignKey("RelatedMediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedMediaFile");
                });
#pragma warning restore 612, 618
        }
    }
}
